version: '3.9'

services:
  db:
    container_name: postgres_container
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=db-btf5q
    ports:
      - 6455:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}